### ISSUE TITLE
Token size on DB

### ISSUE THREAD

**Issue by jackouille-ch** [netniV/plugin_tokenauth#1]
I install and test like you wrote but it's not working.
While checking user token I see that public key is not complete:
![image](https://user-images.githubusercontent.com/35721406/44105591-78b5b18a-9ff2-11e8-9f36-1fc4492b16d7.png)

Could this be the root cause?

I generate a 4096 bits key and here is the full public key:
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmeyZV0ebwcEsgympa53A
4dr0wUHLqAu8i5AWrTQKafqCW2nv4XvrKuh7yk5a/4AlIPoduoY7AhAoUFxqXkeu
iGZqtPlIduoLFBDPQWFlfwU2mBIzcptvCvHI01x4Es8Rft9p8dujiA0rtHWk+Y1u
V9aZS8P9BsrVXp/arIa81E8GAB66DpJ04+K65DTiKD1IoIWPFIK6ZlvUcEaEjhEo
r0qLKPb92wazullpezOYarbsBbV8VaL9r2KQ/Ckg0v1bpT/iOc8uxLzgt0xi/WLw
CKPk/WJri1+9Lv16s+lNjyE4oC4l+DQ6+n21CDM3SiUfooF++9FnvN8liizjs2oJ
Zwt1KAOSr1y3NWJ/eVc1BQPhToujibl4KKQO3yLj0nnzRmZzvVT9ESbUy7CDq5v7
dE4JsNLNa3lznScNV73w0/+Cizkbd9aJgwufcqgMDWPUnNl68vyWuSGT0El3AMyC
guMPEiMkzvMBsNRL50e+8XNlRe8DdYm6nXmGs3vvLsnf+SCx5MdJ4X1ylp0aq9BT
km46p/9/v73sWfALKfLsKJoFzmoMHVStlpn13XP1FAabSFqz8w8gbWYJlknJFZ/g
9pXh72Q0ZhDStbWUGbbQMDpxmhmtUfa7L3tvrnQSrg2ccJTwmXPUFCRSB6pyu6QJ
mw6QxEqGsrSkhs7rB/OfLuMCAwEAAQ==
-----END PUBLIC KEY-----

Ok saw in DB that you allow only 300 chars:
![image](https://user-images.githubusercontent.com/35721406/44105757-fdea5090-9ff2-11e8-98ad-8bf294e3c519.png)

And my public key has 814 chars, increasing DB to 1000

**Comment by netniV** [comment]
That is a mistake of mine between the time of developing it and releasing it I had noticed this issue myself.  However, it would appear that the installer code wasn't updated to match the DB:

```sql
`token` varchar(3000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
```

Mine was set to 3000 to allow room, but on balance, 1000 should be enough.  I've incremented the version number to signify the two updates.
