### ISSUE TITLE
Enhancement: add an autoclose option to Cacti

### ISSUE THREAD

**Issue by jackouille-ch** [netniV/plugin_tokenauth#5]
It could be great to Add an option in Cacti to autoclose itself (after token has been generated) with an option autoclose=1 for example within logon URL. It will give the following: https://cacti.mydomain.ch/cacti/?tokenauth_id=$id&tokenauth_token=$signature&autoclose=1

**Comment by netniV** [comment]
I think it would be better to offer a local redirect once auth is successful?

I would have thought that if you called the auth url via JS, you wouldn't need to autoclose.

**Comment by jackouille-ch** [comment]
You can forget autoclose, I am now using directly autologin within Graphs and here is what I did:
// Checks for autologin
$cactidata=file("https://cacti.net/cacti/graph_view.php"); // Get Cacti Page
for ($csearch=1; $csearch<sizeof($cactidata); $csearch++) {
	if (strpos(" ".$cactidata[$csearch],"Password")>0) { // Searching is current page needs a Password, meaning not logged yet
		$csearch=sizeof($cactidata);
		$autologin=cactiautologin($useridx);
		$link.="&".$autologin;
	}
}

echo "<img src='$link' alt='".$legend['title']."' width=580 height=310></a></td>";

And this works fine, many thanks.

The only caveat is that when this check is performed (filling $cactidata), I receive the following log entry:
2020/05/03 11:54:08 - CMDPHP plugin_tokenauth: No user session found 

But graphs are displayed correctly.

So my question is: can I use another link to check if user is logged (smallest size needed) or how can I avoid this error, or maybe could you update tokenauth?

**Comment by netniV** [comment]
You are only seeing that because you have your log verbosity set to high, or you have the plugin flagged as debug.

**Comment by netniV** [comment]
Also, I just thought that if this is so you can display the graphs, you could supply the token auth on the graph image URL, in a similar way that cycle does?

**Comment by jackouille-ch** [comment]
I just try to use the link with token for each graph but then it took much longer and I still get one log entry, despite I have 9 graphs loaded in the same time.
Any other idea ?

**Comment by netniV** [comment]
Hmm, thinking about it, each request would likely create a new session as the session state is being stored anywhere, unless you are handling that across requests.

**Comment by netniV** [comment]
So I gave this more thought and I think your approach works better.  What I might do is to create a page that simply returns the authentication status as a json file, that way you can get the status of an autologin returned, then just include the rest in a normal way.

**Comment by jackouille-ch** [comment]
Great, thanks for your feedback, it might be faster than waiting for a graph generation as I did actually
Maybe what you can do is checking if session is already active and if not use passed credential to create the session and return simply OK if session is active (newly created or existing) or Fail in case of bad credentials.

**Comment by netniV** [comment]
Yeah, that is what I was thinking along the lines of.

**Comment by netniV** [comment]
This should now be available using https://github.com/netniV/plugin_tokenauth/commit/8b59317fc71be3ce3dd38cbf41f8be931df77fb4
